---
title: "Cleaning the Data"
author: "Sean Kerr"
date: "2023-11-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Tasks:
- Standardize vaults ('VT', 'VT1', and 'VT2')
- Filter out score == 0
- Standardize names
- Standardize horizontal bars ('hb' and 'HB')
- Remove unnecessary columns (Competition, Location, D_Score, E_Score, Penalty)



```{r}
library(tidyverse)
dat <- read.csv('./data_2022_2023.csv')


datclean <- dat %>% 
  mutate(Apparatus = ifelse(Apparatus %in% c('VT', 'VT1', 'VT2'), 'VT', Apparatus)) %>%
  filter(Score != 0) %>%
  mutate(FirstName = toupper(FirstName), LastName = toupper(LastName)) %>%
  mutate(Apparatus= ifelse(Apparatus == 'hb', 'HB', Apparatus)) %>%
  select(LastName, FirstName, Gender, Competition, Country, Date, Round, Apparatus, Rank, Score)


men <- datclean %>% filter(Gender == 'm')

women <- datclean %>% filter(Gender == 'w')

write.csv(x = men, "cleaned_mens_data.csv")
write.csv(x = women, "cleaned_womens_data.csv")
```


